/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 RubberDuck.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/RubberDuck.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RubberDuck_mesh.geometry} material={materials.RubberDuck_mat1} />
    </group>
  )
}

useGLTF.preload('/RubberDuck.glb')
